name: Deploy to staging and production

on:
  push:
    branches:
      - master

permissions:
  contents: read
  deployments: write

jobs:
  reviewapp:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      BUILD_ID: master

    steps:
    - uses: actions/checkout@v1
    - name: Install cf client
      env:
        CF_CLI_VERSION: v7
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=${CF_CLI_VERSION}" | tar -zx -C $GITHUB_WORKSPACE/bin
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
    - name: Build Docker Image
      run: |
        docker login -u=${{ secrets.DockerHubUsername }} -p=${{ secrets.DockerHubPassword }}
        docker build -t beisopss/antivirus:$BUILD_ID .
        docker push beisopss/antivirus:$BUILD_ID
    - name: Deploy to staging
      env:
        SPACE: staging
        CF_USERNAME: ${{ secrets.PaaSUsernameStaging }}
        CF_PASSWORD: ${{ secrets.PaaSPasswordStaging }}
        MANIFEST: manifest.yml
      run: |
        cf api api.london.cloud.service.gov.uk
        cf auth
        cf target -o 'beis-opss' -s $SPACE
        ./deploy.sh
        cf logout
    - name: Deploy to production
      env:
        SPACE: prod
        CF_USERNAME: ${{ secrets.PaaSUsernameProduction }}
        CF_PASSWORD: ${{ secrets.PaaSPasswordProduction }}
        MANIFEST: manifest.yml
      run: |
        cf api api.london.cloud.service.gov.uk
        cf auth
        cf target -o 'beis-opss' -s $SPACE
        ./deploy.sh
        cf logout
