name: Deploy to staging and production

on:
  push:
    branches:
      - master

jobs:
  reviewapp:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      BUILD_ID: master

    steps:
    - uses: actions/checkout@v1
    - name: Install cf client
      env:
        CF_CLI_VERSION: 7.0.0-beta.25
      run: |
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=${CF_CLI_VERSION}" | tar -zx -C /tmp
        sudo cp /tmp/cf7 /usr/local/bin/cf7
    - name: Build Docker Image
      env:
        CF_CLI_VERSION: 7.0.0-beta.25
      run: |
        docker login -u=${{ secrets.DockerHubUsername }} -p=${{ secrets.DockerHubPassword }}
        docker build -t beisopss/antivirus:$BUILD_ID .
        docker push beisopss/antivirus:$BUILD_ID
    - name: Deploy to staging
      env:
        SPACE: staging
        CF_USERNAME: ${{ secrets.PaaSUsernameStaging }}
        CF_PASSWORD: ${{ secrets.PaaSPasswordStaging }}
      run: |
        cf7 api api.london.cloud.service.gov.uk
        cf7 auth
        cf7 target -o 'beis-opss' -s $SPACE
        ./deploy.sh
        cf7 logout
    - name: Deploy to production
      env:
        SPACE: prod
        CF_USERNAME: ${{ secrets.PaaSUsernameProduction }}
        CF_PASSWORD: ${{ secrets.PaaSPasswordProduction }}
      run: |
        cf7 api api.london.cloud.service.gov.uk
        cf7 auth
        cf7 target -o 'beis-opss' -s $SPACE
        ./deploy.sh
        cf7 logout
